// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC06s9FpF65KeDv6elsHdfjDA_YxuBgJ68',
    appId: '1:242594407081:web:8303e13b980d39ce137fb8',
    messagingSenderId: '242594407081',
    projectId: 'advmobprog-firebase-7d5d3',
    authDomain: 'advmobprog-firebase-7d5d3.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-7d5d3.firebasestorage.app',
    measurementId: 'G-W6HTWEX3QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSoR5nk8Oo-eKMx42DeQ8l-8RCoNFEl0M',
    appId: '1:242594407081:android:c505109c235c3baf137fb8',
    messagingSenderId: '242594407081',
    projectId: 'advmobprog-firebase-7d5d3',
    storageBucket: 'advmobprog-firebase-7d5d3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBacqOde_NpwwFjrpDRszLIhWbhgOsW7dg',
    appId: '1:242594407081:ios:a1a934f1e86d0e20137fb8',
    messagingSenderId: '242594407081',
    projectId: 'advmobprog-firebase-7d5d3',
    storageBucket: 'advmobprog-firebase-7d5d3.firebasestorage.app',
    iosBundleId: 'com.example.tuazonAdvmobprog',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBacqOde_NpwwFjrpDRszLIhWbhgOsW7dg',
    appId: '1:242594407081:ios:a1a934f1e86d0e20137fb8',
    messagingSenderId: '242594407081',
    projectId: 'advmobprog-firebase-7d5d3',
    storageBucket: 'advmobprog-firebase-7d5d3.firebasestorage.app',
    iosBundleId: 'com.example.tuazonAdvmobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC06s9FpF65KeDv6elsHdfjDA_YxuBgJ68',
    appId: '1:242594407081:web:c77ce91bf60e4842137fb8',
    messagingSenderId: '242594407081',
    projectId: 'advmobprog-firebase-7d5d3',
    authDomain: 'advmobprog-firebase-7d5d3.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-7d5d3.firebasestorage.app',
    measurementId: 'G-GFQT8N1ZNZ',
  );
}
